networks:
  polydraw:

services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - 6969:80
    networks:
      - polydraw
    depends_on:
      - server

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    volumes:
      - ./server/logs:/app/logs
    networks:
      - polydraw    